eureka:
  instance:
    prefer-ip-address: true
    # hostname: eureka.test.com
    port: 7001
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    secure-port-enabled: true
    non-secure-port-enabled: false

    home-page-url: http://${spring.cloud.client.ip-address}:${server.port}/
    status-page-url-path: http://${spring.cloud.client.ip-address}:${server.port}/actuator/info
    health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/health

    lease-renewal-interval-in-seconds: 5  # 心跳间隔，5秒
    lease-expiration-duration-in-seconds: 10 # 没有心跳的淘汰时间，10秒
  client:
    registry-fetch-interval-seconds: 5 # 定时刷新本地缓存时间
    service-url:
      defaultZone: http://${spring.cloud.client.ip-address}:${eureka.instance.port}/eureka/
