server:
  port: 7005

spring:
  application:
    name: study-demo2

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://${spring.cloud.client.ip-address}:${eureka.instance.port}/eureka/
  instance:
    port: 7001
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true

