spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver #mysql驱动
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: etoak

  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 6000
    jedis:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 1
        max-wait: -1
    password:

eureka:
  instance:
    port: 7001
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5  # 心跳间隔，5秒
    lease-expiration-duration-in-seconds: 10 # 没有心跳的淘汰时间，10秒
  client:
    registry-fetch-interval-seconds: 5 # 定时刷新本地缓存时间
    service-url:
      defaultZone: http://${spring.cloud.client.ip-address}:${eureka.instance.port}/eureka/

info:
  app.name: ${spring.application.name}
  company.name: study.com
  build.groupId: "@project.parent.groupId@" ##yml文件用@，properties文件用$ resource.filtering必须设置为true
  build.artifactId: "@project.artifactId@"
  build.version: "@project.version@"