server:
  port: 7003

spring:
  application:
    name: study-auth-jwt
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver #mysql驱动
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: etoak
  main:
    allow-bean-definition-overriding: true

  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:mapper/*.xml


eureka:
  instance:
    port: 7001
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5  # 心跳间隔，5秒
    lease-expiration-duration-in-seconds: 10 # 没有心跳的淘汰时间，10秒
  client:
    registry-fetch-interval-seconds: 5 # 定时刷新本地缓存时间
    service-url:
      defaultZone: http://${spring.cloud.client.ip-address}:${eureka.instance.port}/eureka/

info:
  app.name: ${spring.application.name}
  company.name: study.com
  build.groupId: "@project.parent.groupId@" ##yml文件用@，properties文件用$ resource.filtering必须设置为true
  build.artifactId: "@project.artifactId@"
  build.version: "@project.version@"